domains:
  cs:
    name: "Computer Science"
    categories:
      AI: "Artificial Intelligence"
      LG: "Machine Learning"
      CL: "Computation and Language"
      CV: "Computer Vision and Pattern Recognition"
      IR: "Information Retrieval"
      NE: "Neural and Evolutionary Computing"
      RO: "Robotics"
      SE: "Software Engineering"
      DB: "Databases"
      CY: "Computers and Society"
      CR: "Cryptography and Security"
  astro-ph:
    name: "Astrophysics"
    categories:
      GA: "Astrophysics of Galaxies"
      CO: "Cosmology and Nongalactic Astrophysics"
      SR: "Solar and Stellar Astrophysics"
      HE: "High Energy Astrophysical Phenomena"
      EP: "Earth and Planetary Astrophysics"
      IM: "Instrumentation and Methods for Astrophysics"
  physics:
    name: "Physics"
    categories:
      comp-ph: "Computational Physics"
      optics: "Optics"
      data-an: "Data Analysis, Statistics and Probability"
      plasm-ph: "Plasma Physics"
      app-ph: "Applied Physics"
      atom-ph: "Atomic Physics"
      bio-ph: "Biological Physics"
  math:
    name: "Mathematics"
    categories:
      CO: "Combinatorics"
      NT: "Number Theory"
      AG: "Algebraic Geometry"
      MP: "Mathematical Physics"
      PR: "Probability"
      ST: "Statistics Theory"
  q-bio:
    name: "Quantitative Biology"
    categories:
      GN: "Genomics"
      NC: "Neurons and Cognition"
      QM: "Quantitative Methods"
  econ:
    name: "Economics"
    categories:
      EM: "Econometrics"
      GN: "General Economics"
      TH: "Theoretical Economics"
  eess:
    name: "Electrical Engineering and Systems Science"
    categories:
      SP: "Signal Processing"
      SY: "Systems and Control"
      AS: "Audio and Speech Processing"
